{%set version = "1.3" %}

package:
  name: speaklater
  version: {{ version }}

source:
  fn: speaklater-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/speaklater/speaklater-{{ version }}.tar.gz
  sha256: 59fea336d0eed38c1f0bf3181ee1222d0ef45f3a9dd34ebe65e6bfffdd6a65a9

build:

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - speaklater

about:
  home: http://github.com/mitsuhiko/speaklater
  license: BSD 3-Clause
  summary: 'Implements a lazy string for python useful for use with gettext'

extra:
  recipe-maintainers:
    - pmlandwehr
