{% set name = "speaklater" %}
{% set version = "1.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "59fea336d0eed38c1f0bf3181ee1222d0ef45f3a9dd34ebe65e6bfffdd6a65a9" %}
{% set build = 3 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - speaklater

about:
  home: http://github.com/mitsuhiko/speaklater
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Implements a lazy string for python useful for use with gettext'
  dev_url: http://github.com/mitsuhiko/speaklater

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
