# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kIjmrFKQ9MLtyJQxDHaMPLrS6arzLMyJ6jbBR4jvavZmPCLeGdBMvOtMlgWbiMgrkY+OKhoEpZ8QYf1joXkN/1QFshIq1+Nacou0tvdRaey3FALN3aS7Lkw0CdaG3UBh6yu8sNkLdFAONnwgJbReeySwCDCSt0UdoqKLhrYNiRUFkPgLgbVqrFgW4AVQBdC2KNiIn7H5sre/4IrfL+ixe+9PesKy79ECrKW79GJL8ILA792k+nvAbBSisA9JtOAEKAhoMcN4G2Vd1uAKsM9vLiODfBjPkxgy93CwEYR95gi2SXLOErBaHlbpVaY4tQCOl/s8YrR6+BXjB6tx/Y50fHKalnybutd+vAR/7yvGN0f3uUNlhvFDsL2RoFMOOc1l0PuwqPEh7pvyOlkqa3r8WQBpfZs3rflPk7Ce2tXO5q2rca8oYsRvFxf0wiqZyQ1wAETxTd9FegMXeAZ0pGP5lbQieL+rnddfJuBJb13qDN7LIKBiyGaXp9vDx1pPxynd1W1oJDy4IF4Tn8aGS7HDq/V0rNr4CfADQx7FPmb6l5wZPoCfWGOLpBwPZ7VMLOxBSzJUV67e1yfdCs2oQ+4ehcqB9n+meEJTRJilSKDZ4yDgfKOT70nQXGVkMU4zLaYivny9siiqlIH9IK6ej/N5Z73sPxuZk+ezpUOy0Su59og="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
