travis:
  secure:
    BINSTAR_TOKEN: fYYW/nU2OhlGXzj5Ua5BK2utOxLacmldhzTPfHE4XXUXsQYRs5TSKpycGSJ6qrzGHpQBi7dsY4s7cWF8f2jnuiyz51i7rzgshp/oAysd65F0ekLMOfz6OGkbjvOW6T82ctOqEq/u+JKB9NxIKhBjuzc+ak05BryUxmgwFI2BZmHoNSQiapUPMst+CM86MEcrZpC/1Ez9pIe8gCR7JZJHpOpqMhl+k6iyECd/+YT0wF9PNi/8KPR1JVGjr2dKa3m/WPuIZvlrD7cKZtRNIfNF3Vk4Sb14zIzHgqSkMmuoDdwWAjieAxIZA4J+sVg1JfczEvIAZq1mXNGkph3SqORFJsO3NGQEalBYNjiqgdt0a2uaCKXMgPnMJ3huQoHzOm/UBNTbcZJ28+x26g6MYpPFg/6+ZVSGRrbb046+pELlcVReOLDptM9jDI8mdLGEKewe36Sa6C7LlbpuhZtva7UCEMS2nA1aVqOyX7eO4aPYl3EBbwkj4rkCGZXVBEjBbFMEEk1rLPnCgXW2+7MFDwqIZ0wAMt551tUe3L2OAv10ri6oU9+jpGHtUzSEyFS6D4h1PpVl5VnujsiRkMa1XmqKB3C6jpjcginmJ9E0EfFoITbqr50WO42mJfpFzHpL/dgZX/ar1vZWyMrx7zh1sKW1FQZl/EYEWgyljJtwAyMW4tg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
