travis:
  secure:
    BINSTAR_TOKEN: gh1USYm8BlfmlX8QxruAkkYyFduOvuOCWnEtqxRO8bPNln2AtkN/XT0G1P4FpTadZxilJlPRXqbZA1Ho6hON61ALbGx2+Z9zMkLAOZSrhqkK1f0IE8SnhhKbFzLsllzUNUQchpFZezdmifZCpDLWsAvs/llzrE86tTcO0mepWbejsr5FF6r2JRWLkonH1krR4BNysmj/Ij4yGdRIsgC1LnV6g24/F8VY4Sh5nB91FVIxueuitb+lJM747oxjxTGBgvCDFOovcOkyut4QJVOih9C3pkuZVs3hePKQfk5QQFN5nAdSc0L4lKXBqbq9AGdShG6P2GQllj53opCHt6KtuTh5U34LLkWBe9TWNw4GYmu8t4uuB7Eudp0a/aNTgKI9K6Be33YZxptFpwPf9RfTTd9bRLtfPmFnRJdCom/jKUm/LYg3bKRzYsQJDiXTQABqUgY6JZOrWK2P2FFuOpmrbg4WnsrnkB85RocbuCBU5bc6nxjUCFYVbE+rEphtgAqqrsvZ6ws3ASMFZIcnw3Mf2TfsUJ4BcZuwD0LkmkHwMnHm3lqKDK+96U3qxIhoc50RVufgWU7UOuS+14Hu1QZ4V+c6hCmhNVpigM+IYiMQ+BwiP7xaWE4BnQYxZ463YGy19dmtxhvAcr8HEEGh+C+qJmnIZ5/04fysjhaJUfcelRI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
