travis:
  secure:
    BINSTAR_TOKEN: AJmDgsmds8AFaIPpCK1F+mQrVlu2Fa6EYWYdigd7A+YBfFz2gmhVAnr314Edd/psRY7TcE+RAkgu6nPmXzqp6SNsXUvnAuwJpJNBssJCe+60aswtNjS+wPJdebUZrCcxHSlxhyr1JVMO/mHUpsnBQjl6afmxTuotiWwZNQaXMjhnzrWejbEtJGb6wUvdks+tTzF+w9f1wEaIWrcfLZuYIiE7VDytDNnxApN8Ge1GvOWCcrC2axZdQ1eZG2VXTvnl3dxIXWCHOyOzhX1iZ5vY9tHpAb5FCxRNQLeF4WdTLeYUt0vvVCI4cEsY46DdWB7n5JhaYy3VgJJQVjPpowKriJOL7MyBjuVgF259STnqB5tfYOUtEFUpb+0T219NXFr63nHuVA9iPnrXoCppd9nl3XwoyQ5iEKDzVfl1SL+YH6LxFv7IsZWyo1NIzt3o3BSQWvYGQLjzrjR/BLfsgy8uEs54Nd9baT9rTVrybmXZyE5Ttd/xeST3bxNH4bOnsHgykDN4gmBhe6Ff9FQmvSKupdG2oxmZe/kLDl5Ec3vOU2DO+ijN5KZ6rbfqJ08GEcBmFaAZpj1v/gHC3CjIIu3VuR4O52i6nnypGbWVn9H6M8HB8JyBYW9lqIbh6aiBf52AIx/a/8hMN7KLcRYil8JDSYmDHqS+r+79wewyNZY7h3M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
